# Generated by Django 3.1.7 on 2021-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controls',
            name='other',
            field=models.TextField(default='Other comments'),
        ),
    ]
