# Generated by Django 3.1.7 on 2021-04-27 07:59

from django.db import migrations, models
import sw_bridge.models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_bridge', '0002_auto_20210427_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncwarecontrol',
            name='host',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='syncwarecontrol',
            name='code',
            field=models.CharField(default=sw_bridge.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
