# Generated by Django 3.1.7 on 2021-04-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_bridge', '0003_auto_20210427_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncwarecontrol',
            old_name='name',
            new_name='username',
        ),
    ]
